# NumPy Basics

In [2]:
# Importing
import numpy as np

## Creation of np.array

In [3]:
# Creation of np.array from list
list_a = [1, 2, 3]
a = np.array(list_a)
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
# 2D array
list_b = [[1, 0, 0],
          [0, 1, 0],
          [0, 0, 1]]
b = np.array(list_b)
print(b)
print(type(b))
print(b.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
(3, 3)


In [5]:
# To create arrays of 0s and 1s
zero_array = np.zeros((2,3))
one_array = np.ones((3,4))
print(zero_array)
print(one_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Generating random numbers
c = np.random.randint(low=1, high=10, size=(3,3))
d = np.random.rand(8, 3)
e = np.random.random_sample((3, 4))
print(c)
print(d)
print(e)

[[1 1 4]
 [5 3 6]
 [8 7 4]]
[[0.41718186 0.0752013  0.89934356]
 [0.26608351 0.02191446 0.43111756]
 [0.76090979 0.15356668 0.19739234]
 [0.17014581 0.68111581 0.21613595]
 [0.34971781 0.48886747 0.65389094]
 [0.75504184 0.66351358 0.21273325]
 [0.42142349 0.06839704 0.14951432]
 [0.34635775 0.00425417 0.66819365]]
[[0.82901708 0.58554994 0.59145447 0.03323338]
 [0.2012338  0.37555683 0.38705551 0.94423968]
 [0.23801588 0.77172834 0.34184194 0.95655121]]


## Reshaping arrays

In [7]:
# Reshaping arrays into required shape
d_1 = np.reshape(d, newshape=(6, 4))
# In order to reshape from 8x3 to 6x4, size can also be mentioned as (6, -1)
# The remaining factor (in place of -1) is automatically computed
d_2 = d.reshape((6, -1))
print(d_1)
print(d_2)
print(d_1 == d_2)

[[0.41718186 0.0752013  0.89934356 0.26608351]
 [0.02191446 0.43111756 0.76090979 0.15356668]
 [0.19739234 0.17014581 0.68111581 0.21613595]
 [0.34971781 0.48886747 0.65389094 0.75504184]
 [0.66351358 0.21273325 0.42142349 0.06839704]
 [0.14951432 0.34635775 0.00425417 0.66819365]]
[[0.41718186 0.0752013  0.89934356 0.26608351]
 [0.02191446 0.43111756 0.76090979 0.15356668]
 [0.19739234 0.17014581 0.68111581 0.21613595]
 [0.34971781 0.48886747 0.65389094 0.75504184]
 [0.66351358 0.21273325 0.42142349 0.06839704]
 [0.14951432 0.34635775 0.00425417 0.66819365]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [8]:
# Task: Try to reshape the array into a 3D array of shape 2x3x4

## Deletion of elements

In [9]:
# Deletion of rows/columns
d_col_delete = np.delete(d, 1, axis=1)
d_row_delete = np.delete(d, 2, axis=0)
print(d_col_delete.shape)
print(d_row_delete.shape)

(8, 2)
(7, 3)


In [10]:
# Learn the concepts of axis properly
# Check StackOverflow or NumPy documentation for more details

In [11]:
# Task: Delete a particular element of array `c`

## Merging Rows or Columns

In [12]:
# Merging Rows/Columns
merge_rows = np.vstack((c, d))
merge_cols = np.hstack((c, e))

In [15]:
print(merge_rows)

[[1.00000000e+00 1.00000000e+00 4.00000000e+00]
 [5.00000000e+00 3.00000000e+00 6.00000000e+00]
 [8.00000000e+00 7.00000000e+00 4.00000000e+00]
 [4.17181855e-01 7.52012995e-02 8.99343561e-01]
 [2.66083506e-01 2.19144593e-02 4.31117564e-01]
 [7.60909786e-01 1.53566681e-01 1.97392342e-01]
 [1.70145806e-01 6.81115808e-01 2.16135945e-01]
 [3.49717808e-01 4.88867468e-01 6.53890941e-01]
 [7.55041843e-01 6.63513584e-01 2.12733245e-01]
 [4.21423494e-01 6.83970437e-02 1.49514321e-01]
 [3.46357751e-01 4.25417341e-03 6.68193647e-01]]


In [16]:
print(merge_cols)

[[1.         1.         4.         0.82901708 0.58554994 0.59145447
  0.03323338]
 [5.         3.         6.         0.2012338  0.37555683 0.38705551
  0.94423968]
 [8.         7.         4.         0.23801588 0.77172834 0.34184194
  0.95655121]]


In [ ]:
# Task: Try using np.concatenate to perform the above operations

# Aggregate Functions

In [ ]:
# Task: Find the row-wise minimum of the array `c`
# Task: find the column-wise mean of array `d`
# Task: Find the row-wise mean of array `e`
# Task: Find the maximum of all values in the array `c`